# Generated by Django 4.1.6 on 2023-06-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeTags',
            new_name='HomeTag',
        ),
        migrations.RenameModel(
            old_name='InteriorDesignTags',
            new_name='InteriorDesignTag',
        ),
    ]
