# Generated by Django 4.1.6 on 2023-06-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_hometags_hometag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='tag',
            field=models.ManyToManyField(to='backend.hometag'),
        ),
        migrations.AlterField(
            model_name='interiordesign',
            name='pic',
            field=models.ImageField(upload_to='home_pics'),
        ),
        migrations.AlterField(
            model_name='interiordesign',
            name='tag',
            field=models.ManyToManyField(to='backend.interiordesigntag'),
        ),
    ]
