# Generated by Django 4.1.6 on 2023-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_home_tag_alter_interiordesign_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interiordesign',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
