# Generated by Django 4.1.6 on 2023-06-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_aggregateddata_customer_service_design_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
