# Generated by Django 4.1.6 on 2023-06-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_order_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregateddata',
            name='total_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
