# Generated by Django 4.1.6 on 2023-06-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_service_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregateddata',
            name='profit_per_service',
        ),
        migrations.AddField(
            model_name='service',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
