# Generated by Django 4.1.6 on 2023-06-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='handycreations@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
